/**
 * Job priority levels
 * Lower number = higher priority (processed first)
 */
export enum JobPriority {
  CRITICAL = 1, // Verification codes, password resets, invites
  HIGH = 2, // Security alerts, account lockout
  NORMAL = 3, // General notifications
  LOW = 4, // Marketing, digest emails
}

/**
 * Base job data structure
 * All job types should extend this interface
 */
export interface BaseJobData {
  /**
   * Unique identifier for the job
   * Auto-generated by BullMQ
   */
  jobId?: string;

  /**
   * Job priority (1-4)
   * @default JobPriority.NORMAL
   */
  priority?: JobPriority;

  /**
   * User ID associated with this job (if applicable)
   * Used for activity logging and auditing
   */
  userId?: string;

  /**
   * Additional metadata for logging/debugging
   */
  metadata?: Record<string, unknown>;
}

/**
 * Email job data structure
 */
export interface EmailJobData extends BaseJobData {
  /**
   * Recipient email address
   */
  to: string;

  /**
   * Email subject line
   */
  subject: string;

  /**
   * Email template name (for logging/debugging)
   */
  templateName: string;

  /**
   * Serialized React Email component
   * Will be deserialized in worker
   */
  templateHtml: string;

  /**
   * Plain text version of email
   */
  templateText: string;
}

/**
 * Queue job status for database audit trail
 */
export enum QueueJobStatus {
  PENDING = "pending",
  PROCESSING = "processing",
  COMPLETED = "completed",
  FAILED = "failed",
}

/**
 * Queue job record for database
 */
export interface QueueJob {
  id: string;
  queueName: string;
  jobId: string;
  type: string;
  priority: number;
  status: QueueJobStatus;
  attempts: number;
  data: Record<string, unknown>;
  error: string | null;
  completedAt: Date | null;
  createdAt: Date;
}

/**
 * Insert type for queue job
 */
export type QueueJobNew = Omit<QueueJob, "id" | "createdAt">;
